kits:
  pvp:
    menuItem: DIAMOND_SWORD 1 DAMAGE_ALL:1
    menuName: KIT PVP
    menuColorCode: f
    menuLore: The standard kit for pvp
    items:
    - DIAMOND_SWORD 1 DAMAGE_ALL:1
    armor:
    - IRON_HELMET 1
    - IRON_CHESTPLATE 1
    - IRON_LEGGINGS 1
    - IRON_BOOTS 1
  archer:
    menuItem: BOW 1 ARROW_DAMAGE:3
    menuName: KIT ARCHER
    menuColorCode: b
    menuLore: Archer set
    items:
    - IRON_SWORD 1 DAMAGE_ALL:1/KNOCKBACK:2
    - BOW 1 ARROW_INFINITE:1/ARROW_DAMAGE:3/ARROW_KNOCKBACK:2/ARROW_FIRE:1
    - ARROW 1
    armor:
    - IRON_HELMET 1 PROTECTION_PROJECTILE:1
    - IRON_CHESTPLATE 1 PROTECTION_PROJECTILE:1
    - CHAINMAIL_LEGGINGS 1 PROTECTION_ENVIRONMENTAL:2/DURABILITY:3
    - CHAINMAIL_BOOTS 1 PROTECTION_ENVIRONMENTAL:2/DURABILITY:3
  mage:
    menuItem: FIREBALL
    menuName: KIT MAGE
    menuColorCode: 4
    menuLore: Shoot fireballs!
    items: 
    - IRON_SWORD 1 DAMAGE_ALL:1/FIRE_ASPECT:2
    - KITITEM FIREBALL 4:Fireball
    armor:
    - CUSTOM 255:0:0 LEATHER_HELMET PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
    - IRON_CHESTPLATE 1 PROTECTION_FIRE:4
    - CUSTOM 255:0:0 LEATHER_LEGGINGS PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
    - CUSTOM 255:0:0 LEATHER_BOOTS PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
  eagle:
    menuItem: QUARTZ
    menuName: KIT EAGLE
    menuColorCode: 6
    menuLore: Glide around the map!
    items: 
    - STONE_SWORD 1 DAMAGE_ALL:3/DURABILITY:3
    - KITITEM QUARTZ 6:Eagle/Wing
    armor:
    - IRON_HELMET 1 DURABILITY:1
    - CUSTOM 100:67:33 LEATHER_CHESTPLATE PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
    - CUSTOM 100:67:33 LEATHER_LEGGINGS PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
    - CUSTOM 255:255:0 LEATHER_BOOTS PROTECTION_FALL:4/PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
  monk:
    menuItem: BLAZE_ROD
    menuName: KIT MONK
    menuColorCode: e
    menuLore: Break down your opponents!
    items: 
    - WOOD_SWORD 1 DAMAGE_ALL:5/DURABILITY:5
    - KITITEM BLAZE_ROD e:Monk/Staff
    armor:
    - CUSTOM 235:133:9 LEATHER_HELMET PROTECTION_ENVIRONMENTAL:5/DURABILITY:200    
    - CUSTOM 235:133:9 LEATHER_CHESTPLATE PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
    - CUSTOM 235:133:9 LEATHER_LEGGINGS PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
    - IRON_BOOTS 1 PROTECTION_ENVIRONMENTAL:1
  ghost:
    menuItem: NETHER_STAR
    menuName: KIT GHOST
    menuColorCode: e
    menuLore: Turn invisible!
    items: 
    - STONE_SWORD 1 DAMAGE_ALL:4/DURABILITY:3
    - KITITEM NETHER_STAR f:Invisibility/Gem
    armor:
    - CUSTOM 66:65:63 LEATHER_HELMET PROTECTION_ENVIRONMENTAL:5/DURABILITY:200    
    - CHAINMAIL_CHESTPLATE 1 PROTECTION_ENVIRONMENTAL:2
    - CUSTOM 66:65:63 LEATHER_LEGGINGS PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
    - CUSTOM 66:65:63 LEATHER_BOOTS PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
   engineer:
    menuItem: IRON_PLATE
    menuName: KIT ENGINEER
    menuColorCode: a
    menuLore: Place landmines to trap your opponents!
    items: 
    - DIAMOND_AXE 1 DAMAGE_ALL:3
    - KITITEM IRON_PLATE a:Landmine
    armor:
    - CHAINMAIL_HELMET 1 PROTECTION_ENVIRONMENTAL:2   
    - IRON_CHESTPLATE 1 PROTECTION_EXPLOSIONS:4
    - IRON_LEGGINGS 1 PROTECTION_EXPLOSIONS:4
    - CUSTOM 15:50:12 LEATHER_BOOTS PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
  blind:
    menuItem: FLINT
    menuName: KIT BLIND
    menuColorCode: 8
    menuLore: Blind your opponents!
    items: 
    - IRON_SWORD 1 DAMAGE_ALL:3/DURABILITY:3
    - KITITEM FLINT 8:Blinding/Shard
    armor:
    - CUSTOM 0:0:0 LEATHER_HELMET PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
    - CUSTOM 0:0:0 LEATHER_CHESTPLATE PROTECTION_ENVIRONMENTAL:5/DURABILITY:200
    - CHAINMAIL_LEGGINGS 1 PROTECTION_ENVIRONMENTAL:2
    - CHAINMAIL_BOOTS 1 PROTECTION_ENVIRONMENTAL:2
bannedBlocks:
  - chest
  - trapped_chest
  - anvil
  - tnt
  - sulphur
  - hopper
  - dropper
  - lava
  - lava_bucket
  - redstone
  - redstone_block
  - glowstone_block
  - glowstone
  - dispenser
  - storage_minecart
  - command_minecart
  - minecart
  - powered_minecart
  - explosive_minecart
  - hopper_minecart
  - redstone_ore
  - command
  - mob_spawner
  - monster_egg
  - ender_pearl
  - skull_item
  - glowstone_dust
  - nether_stalk
  - brewing_stand
  - blaze_rod
  - magma_cream
  - ghast_tear
  - golden_carrot
  - carrot
  - rabbit_foot
  - blaze_powder
  - sugar
  - sugar_cane
  - spider_eye
  - fermented_spider_eye
  - golden_apple
  - leather_helmet
  - leather_chestplate
  - leather_leggings
  - leather_boots
  - iron_helmet
  - iron_chestplate
  - iron_leggings
  - iron_boots
  - gold_helmet
  - gold_chestplate
  - gold_leggings
  - gold_boots
  - diamond_helmet
  - diamond_chestplate
  - diamond_leggings
  - diamond_boots
  - wood_sword
  - wood_axe
  - iron_sword
  - iron_axe
  - gold_sword
  - gold_axe
  - diamond_sword
  - diamond_axe
  - bow
  - arrow
  - potion
  - glass_bottle
  
  - flint
  - string
  - exp_bottle
  - enchanted_book
  - brown_mushroom
  - red_mushroom
  - bowl
  - egg
  - snow
  - snow_ball
  
  
Players: