kits:
  pvp:
    menuItem: DIAMOND_SWORD 1 DAMAGE_ALL:1
    menuName: KIT PVP
    menuColorCode: f
    menuLore: The standard kit for pvp
    items:
    - DIAMOND_SWORD 1 DAMAGE_ALL:1
    armor:
    - IRON_HELMET 1
    - IRON_CHESTPLATE 1
    - IRON_LEGGINGS 1
    - IRON_BOOTS 1
  archer:
    menuItem: DIAMOND_SWORD 1 DAMAGE_ALL:1
    menuName: KIT ARCHER
    menuColorCode: b
    menuLore: Archer set
    items:
    - IRON_SWORD 1 DAMAGE_ALL:1/KNOCKBACK:2
    - BOW 1 ARROW_INFINITE:1/ARROW_DAMAGE:3/ARROW_KNOCKBACK:2/ARROW_FIRE:1
    - ARROW 1
    armor:
    - IRON_HELMET 1 PROTECTION_PROJECTILE:1
    - IRON_CHESTPLATE 1 PROTECTION_PROJECTILE:1
    - CHAINMAIL_LEGGINGS 1 PROTECTION_ENVIRONMENTAL:2/DURABILITY:3
    - CHAINMAIL_BOOTS 1 PROTECTION_ENVIRONMENTAL:2/DURABILITY:3
bannedBlocks:
  - chest
  - trapped_chest
  - anvil
  - tnt
  - sulphur
  - hopper
  - dropper
  - lava
  - lava_bucket
  - redstone
  - redstone_block
  - glowstone_block
  - glowstone
  - dispenser
  - storage_minecart
  - command_minecart
  - minecart
  - powered_minecart
  - explosive_minecart
  - hopper_minecart
  - redstone_ore
  - command
  - mob_spawner
  - monster_egg
  - ender_pearl
  - skull_item
  
Players: